sudo: required
language: c++
osx_image: xcode10.1
os:
- linux
- osx

env:
  global:
    - TWINE_USERNAME=cmeyer
    - secure: "XONrATvQccjx3suCW2vnG3my9p7e+ejy4Z6H8ofXzsnU8G+XknviHY5l1GKh9ygQcrc0SGgOYep1L0wIIymhJEP5tf1B+x6h1FAltdhUU9UmiQkCRyH4wFcCLojI8QWXJ4QhjukGlqfmC7jTYsXjX29PZxzyMamc4r5f2kueCu+vzPcz9Rd396LWfYXFy/lraF7/DplB9/GnUQEhZ+PNZM211Lt1FWozY/tj4JzwFKYopKkpX7XKRFwdbLvhFVEr89w4XXD8d94encvAcP2t6NE6KQxt5Z+AmCGYreQhu8HbAGcXJgkiJZBUdM1JM+1o/YoUbNx+jZzYeqPJdXd9DgCI0DZfmkIEN0/0gowIlSqqxvOQkVr5FxY8ygh6TpGLsRq5RWYCh3/IBFISh5SzQhGjwayLskkyQyWsA9tkzajCSOOZ3iNTTo7jUyrQ9S15EH0LMkTYO7hqbj1jRcOWnSXZhQt44xTVvtJdkGowFVfUWXDb818A0OiXwbNoK6p1GZpiQijrzwVpNKnq23gzeYxzezODFmweiLRAfwlsiVuHRjjk/U4tOPkhEVK0oV8/VtZpCkimIcwtvKBFeJFvlIWh7MBuOZfTQXB34GwZO1TFwseUF96QsUZpegXdCZgSwnPRv8I8exqo9VduyNIBoyOnHbTSacII3xrqyU4tJg4="

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install numpy==1.15; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '' 's/QTDIR = $(HOME)\/Developer\/Qt\/5.12.0\/clang_64/QTDIR = \/usr\/local\/opt\/qt5/g' launcher/xcconfig/targetReleaseNionUILauncher.xcconfig; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '' 's/PYTHONHOME = $(HOME)\/Developer\/miniconda43/PYTHONHOME = \/usr\/local\/opt\/python3\/Frameworks\/Python.framework\/Versions\/3.7/g' launcher/xcconfig/targetReleaseNionUILauncher.xcconfig; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - python3-dev

script:
  bash travis-build.sh

after_success:
  # if tagged, create the source distribution and upload to PyPI
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      cd ${TRAVIS_BUILD_DIR}
      pip3 install twine
      twine upload dist/*.whl
    fi
