package:
  name: 'nionui-tool'
  version: '0.3.17'

source:
  - path: nion
    folder: nion
  - path: setup.py
  - path: NionUILauncher-Mac.zip  # [osx]
  - path: NionUILauncher-Windows  # [win64]
    folder: NionUILauncher-Windows  # [win64]
  - path: NionUILauncher-Linux.zip  # [linux64]

build:
  number: 0
  include_recipe: False
  entry_points:
    - nionui-tool = nion.nionui_tool.command:main

requirements:
  host:
    - python {{ python }}
    - setuptools
  run:
    - python >=3.5

about:
  home: https://github.com/nion-software/nionui-tool
  license: GPL-3.0
  summary: Nion UI native launcher.
  description: "A native launcher for Nion UI apps."

extra:
  recipe-maintainers:
    cmeyer
