name: Build (macOS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      shell: bash
      run: |
        python -c "import sys; print(sys.version)"
        python -c "import sys; print(sys.executable)"
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.1'
        host: 'mac'
        target: 'desktop'
    - name: Build
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install install packaging
        python -m pip install install numpy
        pushd launcher
        PYTHON=`python -c "import sys; print(sys.executable, end='')"`
        cmake CMakeLists.txt -DPython3_EXECUTABLE="$PYTHON"
        cmake --build . --config Release
        mkdir -p build/Release
        mv build/*.app build/Release
        popd
        python setup.py bdist_wheel
    - name: Set up Miniconda ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Build Conda Package
      shell: bash -l {0}
      run: |
        python -c "import sys; print(sys.version)"
        python -c "import sys; print(sys.executable)"
        conda install conda-build -y
        conda build ./.github/workflows/recipe
    - name: Upload Wheel
      uses: actions/upload-artifact@v2
      with:
        name: nionui-tool-macos-whl-${{ matrix.python-version }}
        path: dist/*.whl
    - name: Upload Conda Package
      uses: actions/upload-artifact@v2
      with:
        name: nionui-tool-macos-conda-${{ matrix.python-version }}
        path: /usr/local/miniconda/envs/test/conda-bld/osx-64/*.tar.bz2
